export const GET_UNIT_REQUEST = "GET_UNIT_REQUEST"
export const GET_UNIT_REQUEST_SUCCESS = "GET_UNIT_REQUEST_SUCCESS"
export const SET_FILTERED_UNITS = "SET_FILTERED_UNITS"
export const SET_UNIT_FOR_DETAILS = "SET_UNIT_FOR_DETAILS"